title: Menubar Apps
description: A collection of useful menubar applications for your Mac
url: https://menubar-apps.github.io
baseurl: ""

collections:
  main:
    output: true
  widgets:
    output: true

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

# Social links for SEO
author: 
  name: Menubar Apps
  twitter: # your-twitter-handle
github_username: menubar-apps
